# This workflow will build the Docker image for the application and run the automated tests 

name: Test application

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    
    - name: Build app image
      run: make compose-build
        
    - name: Run tests
      run: make test-all
